eb-django-express-signup/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
# from core import views as core_views
# from core import views as core_views
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('form.urls')),
    # url(r'^$', 'signup', name='home'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^.*$', RedirectView.as_view(url='/', permanent=False), name='index')
]

form/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'form'

urlpatterns = [
    # ex: /
    path('', views.home, name='home'),
    # ex: /signup
    path('signup', views.signup, name='signup'),
    # ex: /privacy
    path('privacy', views.privacy, name='privacy'),
    # ex: /login
    url(r'^login/$', views.login, name='login'),
    # ex: /dashboard
    path('dashboard', views.dashboard, name='dashboard'),
]

form/models.py
import sys
from django.db import models
import boto3
import os
import logging

import time
from calendar import timegm

# back-end tables
STARTUP_SIGNUP_TABLE = os.environ['STARTUP_SIGNUP_TABLE']
AWS_REGION = os.environ['AWS_REGION']
PRICE_LOG = os.environ['PRICE_LOG']

logger = logging.getLogger(__name__)


class Leads(models.Model):

    # sign-up form data
    def insert_lead(self, fromAirport, toAirport, date, email, notifications, username):
        try:
            dynamodb = boto3.resource('dynamodb', region_name=AWS_REGION)
            table = dynamodb.Table(STARTUP_SIGNUP_TABLE)
        except Exception as e:
            logger.error(
                'Error connecting to database table: ' + (e.fmt if hasattr(e, 'fmt') else '') + ','.join(e.args))
            return 403
        try:
            if not username:
                username = "anonymous"
            response = table.put_item(
                Item={
                    'routeID': fromAirport[0:fromAirport.find(",")] + '$' + toAirport[0:toAirport.find(",")] + '$' + date,
                    'date': timegm(time.strptime(date, "%Y-%m-%d")),
                    'lowestPrice': sys.maxsize,
                    'email': email,
                    'username': username,
                    'notifications': notifications,
                },
                ReturnValues='ALL_OLD',
            )
        except Exception as e:
            logger.error(
                'Error adding item to database: ' + (e.fmt if hasattr(e, 'fmt') else '') + ','.join(e.args))
            return 403
        status = response['ResponseMetadata']['HTTPStatusCode']
        if status == 200:
            if 'Attributes' in response:
                logger.error('Existing item updated to database.')
                return 409
            logger.error('New item added to database.')
        else:
            logger.error('Unknown error inserting item to database.')

        return status

    # priceData for chart on dashboard
    def get_priceData(self, routeID):
        try:
            dynamodb = boto3.resource('dynamodb', region_name=AWS_REGION)
            table = dynamodb.Table(PRICE_LOG)
        except Exception as e:
            logger.error(
                'Error connecting to database table: ' + (e.fmt if hasattr(e, 'fmt') else '') + ','.join(e.args))
            return None
        expression_attribute_values = {}
        FilterExpression = []
        if routeID:
            expression_attribute_values[':r'] = routeID
            FilterExpression.append('routeID = :r')
            response = table.scan(
                # FilterExpression=Key('routeID').eq(':r'),
                FilterExpression=' and '.join(FilterExpression),
                ExpressionAttributeValues=expression_attribute_values,
                ProjectionExpression="#dt, price",
                ExpressionAttributeNames={"#dt": "date"}
            )

        if response['ResponseMetadata']['HTTPStatusCode'] == 200:
            return response['Items']
        logger.error('Unknown error retrieving items from database.')
        return None

    # Drop-down menu of dashboard
    def get_routeIDs(self, user):
        try:
            dynamodb = boto3.resource('dynamodb', region_name=AWS_REGION)
            table = dynamodb.Table(os.environ['STARTUP_SIGNUP_TABLE'])
        except Exception as e:
            logger.error(
                'Error connecting to database table: ' + (e.fmt if hasattr(e, 'fmt') else '') + ','.join(e.args))
            return None

        # filter only routes for current user
        expression_attribute_values = {}
        FilterExpression = []
        expression_attribute_values[':u'] = user
        FilterExpression.append('username = :u')
        response = table.scan(
            FilterExpression=' and '.join(FilterExpression),
            ExpressionAttributeValues=expression_attribute_values,
            ProjectionExpression='routeID',
        )

        if response['ResponseMetadata']['HTTPStatusCode'] == 200:
            return response['Items']
        logger.error('Unknown error retrieving items from database.')
        return None

        # # Drop-down menu of dashboard
        # def get_routeIDs(self, username):
        #     try:
        #         dynamodb = boto3.resource('dynamodb', region_name=AWS_REGION)
        #         table = dynamodb.Table(os.environ['PRICE_LOG'])
        #     except Exception as e:
        #         logger.error(
        #             'Error connecting to database table: ' + (e.fmt if hasattr(e, 'fmt') else '') + ','.join(e.args))
        #         return None
        #
        #     # filter only routes for current user
        #     expression_attribute_values = {}
        #     FilterExpression = []
        #     expression_attribute_values[':u'] = username
        #     FilterExpression.append('username = :u')
        #     response = table.scan(
        #         FilterExpression=' and '.join(FilterExpression),
        #         ExpressionAttributeValues=expression_attribute_values,
        #         ProjectionExpression='routeID',
        #     )
        #
        #     if response['ResponseMetadata']['HTTPStatusCode'] == 200:
        #         return response['Items']
        #     logger.error('Unknown error retrieving items from database.')
        #     return None

form/views.py
import os
import random
import string
import boto3
import re
import vincent
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path
import vincent
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render
from social_core.pipeline import user

from .models import Leads

BASE_DIR = getattr(settings, "BASE_DIR", None)


def home(request):
    return render(request, 'signup.html')


def privacy(request):
    return render(request, 'privacy.html')


def login(request):
    return render(request, 'login.html')


# insert the user sign up information into the DynamoDB table "gsg-signup-table"
def signup(request):
    leads = Leads()
    status = leads.insert_lead(request.POST['fromAirport'], request.POST['toAirport'], request.POST['date'], request.POST['email'],
                               request.POST['notifications'],request.POST['username'])
    # if status == 200:
    #     leads.send_notification(request.POST['email'])
    return HttpResponse('', status=status)


# user dashboard: get data for route selection drop-down and chart
def dashboard(request):
    routeID = request.GET.get('routeID')
    user = request.user.username
    leads = Leads()
    if routeID:
        # get chart data for chosen route
        items = leads.get_priceData(routeID)
        pr = [float(i['price']) for i in items if 'price' in i]
        dt = [i['date'] for i in items if 'date' in i]
        data = {'data': pr, 'x': dt}
        print(data)
        bar = vincent.Bar(data, iter_idx='x')
        bar.axis_titles(x='Dates', y='Prices')

        # cleanup function: delete any locally existing priceChart files (from local testings)
        deleteTempFiles(os.path.join(BASE_DIR, 'static'), 'priceChart')

        # generate filename with id based on yyyyMMdd and a random 5-character string to distinguish chart data
        filename = 'priceChart' + generateUniqueName() + '.json';
        bar.to_json(os.path.join(BASE_DIR, 'static', filename))

        # send file to S3
        uploadToS3('priceChart', filename);

        return render(request, 'dashboard.html', {'items': items, 'filename': 'priceChart/' + filename})
    elif user:
        # get routes for drop-down menu
        items = leads.get_routeIDs(user)
        return render(request, 'dashboard.html', {'routeIDs': items})

        # String clean-up, not working yet
        #for item in items:
        #    clean = re.sub('[$]', ' ', item['routeID'])
        #return render(request, 'dashboard.html', {'routeIDs': items, 'cleanName': clean})
    else:
        return render(request, 'dashboard.html')


# function for uploading the chart json file to S3
def uploadToS3(dir, filename):
    bucketName = getattr(settings, "AWS_STORAGE_BUCKET_NAME", None)
    s3 = boto3.resource('s3')
    data = open(os.path.join(BASE_DIR, 'static', filename), 'rb')
    s3.Bucket(bucketName).put_object(Key=dir + '/' + filename, Body=data)


# function for creating unique ID for dashboard chart files
def generateUniqueName():
    date = datetime.now().strftime("%Y%m%d");
    chars = random.choices(string.ascii_lowercase + string.digits, k=5);
    return date + '-' + ''.join(chars);


# cleanup function of old dashboard chart files on S3
def deleteTempFiles(path, prefix):
    for f in Path(path).glob(prefix + "_"):
        fileDateStr = f.name[len(prefix) + 1:f.name.index('-')]
        fileDate = datetime.strptime(fileDateStr, '%Y%m%d')

        # Use >= yesterday as comparison so it doesnt include files created today
        # which may include files still in use
        if fileDate <= datetime.now() - timedelta(days=1):
            os.remove(f)

form/templates/dashboard.html
{% extends "generic.html" %}
{% block contents %}
{% if user.is_authenticated %}
    {% if routeIDs %}
        <h2>Hello, {{ user.get_full_name }}! Welcome to your personal price checker dashboard!</h2>  <p></p>
        <h5> Here you can easily check the price data of your saved route requests.</h5>
        <p></p>
        <p></p>
        <p></p>
        <form>
            <div class="form-group">
                <label for="routeID">Which route would you like to track?</label>
                <select name="routeID" id="routeID" class="form-control">
                    <option selected value="">choose...</option>
                    {% for routeID in routeIDs %}
                        <option value="{{ routeID.routeID }}">{{ routeID.routeID }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit">
            </div>
        </form>
    {% else %}
        {% load static %}
        <head>
            <title>Vega Scaffold</title>
            <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
            <script src="http://d3js.org/topojson.v1.min.js"></script>
            <script src="http://d3js.org/d3.geo.projection.v0.min.js" charset="utf-8"></script>
            <script src="http://trifacta.github.com/vega/vega.js"></script>
        </head>
        <body>
        <h2>Here's a price overview for your selected flight route.</h2>
        <p></p>
        <p>For a detailed price list please refer to the table below.</p>
        <div id="vis"></div>
        </body>

        <script type="text/javascript">
            // parse a spec and create a visualization view
            function parse(spec) {
                vg.parse.spec(spec, function (chart) {
                    chart({el: "#vis"}).update();
                });
            }

            parse('{% static filename %}');
        </script>

        <p></p>
        <p></p>
        <p></p>
        <h2>Price overview table:</h2>
        <p></p>
        <p></p>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Price [€]</th>
            </tr>
            </thead>
            {% for item in items %}
                <tr>
                    <td>{{ item.date }}</td>
                    <td>{{ item.price }}</td>
                </tr>
            {% endfor %}
        </table>
        <p><a class="btn btn-primary" href="{% url 'form:dashboard' %}">Choose another route</a></p>
    {% endif %}
{% else %}

    <h2>Sorry, you need to login first to see this page...</h2>

     <p><a class="btn btn-primary" href="{% url 'form:login' %}">Go to Login</a></p>
{% endif %}
{% endblock %}

form/templates/generic.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Cheap Checker</title>
    <!-- https://www.bootstrapcdn.com/ -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Bootstrap Lumen theme -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.3/lumen/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-lBO0+E/aIJhpRIYjP6dJ1mNYgo3hhUBPcF74XRfOM27g7WmDuitolvnUENdDG4QI" crossorigin="anonymous">
    <!-- Bootstrap fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.min.css">
    <link href="{% static 'custom.css' %}" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
        <a href="../" class="navbar-brand">Cheap Checker</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link active" href="{% url 'form:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'form:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'form:dashboard' %}">Dashboard</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'form:privacy' %}">Privacy Policy</a></li>
                <li class="nav-item"></li>
            </ul>
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'form:dashboard' %}">Welcome {{ user.username }}</a></li>
            </ul>
        </div>
    </div>
</nav>
<main role="main">
    <div class="jumbotron" id="newstartup">

        <div class="container">
            <img src="/static/cheap_checker_logo.png" alt="logo" />
            <img src="/static/Ryanair.svg"  align="right" width="900" />
            <h1 class="display-3">Cheap Checker</h1>

        </div>
    </div>
    <div class="container">
        {% block contents %}<!-- /contents -->{% endblock %}
        <hr>
        <footer id="footer">
            <div class="row">
                <div class="col-lg-12">
                    <p>&copy; Price Checker 2018
                        <span class="pull-right">Made with
                            <a target="_blank" href="http://getbootstrap.com/">Bootstrap 4</a>
                        using <a target="_blank" href="https://bootswatch.com/lumen/">Lumen</a> theme.</span>
                    </p>
                </div>
            </div>
        </footer>
    </div>
</main>
<!-- Jquery Scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Bootstrap core Scripts -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"
        integrity="sha384-feJI7QwhOS+hwpX2zkaeJQjeiwlhOP+SdQDqhgvvo1DsjtiSQByFdThsxO669S2D"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

form/templates/index.html
{% extends "generic.html" %}
{% block contents %}
    <div class="row justify-content-md-center">
        <div class="col-sm-8">
            <div id="signupSuccess" class="alert alert-success" style="display:none">
                <p id="signupSuccessText">Thanks for signing up!<br/>
                    You'll be among the first to know when we launch.</p>
            </div>
            <div id="signupDuplicate" class="alert alert-success" style="display:none">
                <p id="signupDuplicateText">Fear not, you're already on the list!<br/>
                    You'll be among the first to know when we launch.</p>
            </div>
            <div id="signupError" class="alert alert-info" style="display:none">
                <p id="signupErrorText">Well this is embarrassing.<br/>
                    It looks like we're having trouble getting you on the list.</p>
            </div>
            <div class="jumbotron" id="jumbohome">
                <h1>The next big thing is coming...</h1>
                <div class="row">
                    <div class="col-sm-9">
                        <p class="lead">We're pretty thrilled to unveil the subject you always wanted to enroll in.</p>
                        <p>Sign up below to be notified when we officially launch!</p>
                        <p><a class="btn btn-lg btn-success" data-toggle="modal" href="#signupModal">Sign up today</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal" tabindex="-1" role="dialog" id="signupModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Provide a few details and we'll be in touch...</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="signupForm" role="form">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Your name">
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" id="email" name="email"
                                   placeholder="Your email address">
                        </div>
                        <div class="form-group">
                            <label for="previewAccess">Interested in Preview Access?</label>
                            <select class="form-control" name="previewAccess" id="previewAccess">
                                <option>Yes</option>
                                <option>No</option>
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button id="signup" type="button" class="btn btn-primary">Sign Up!</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}

    {% csrf_token %}
    <script type="text/javascript">
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $(document).ready(function () {
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            $("#signup").click(function () {
                $.post("{% url 'form:signup' %}", $("#signupForm").serialize(),
                    function (data) {
                        $("#signupSuccess").show();
                    }
                )
                    .error(function (xhr) {
                        switch (xhr.status) {
                            case 409:
                                $("#signupDuplicate").show();
                                break;
                            default:
                                $("#signupError").show();
                        }
                    })
                    .always(function () {
                        $("#signupModal").modal('hide');
                    });
            })
        })
    </script>

{% endblock %}

form/templates/login.html
{% extends "generic.html" %}
{% block contents %}

    <h2>Login</h2>

        <a href="{% url 'social:begin' 'twitter' %}" title="Twitter" class="btn btn-social btn-md btn-twitter">
            <i class="fa fa-twitter"></i> Sign in with Twitter
        </a>


{% endblock %}
{% block scripts %}
    {% csrf_token %}

{% endblock %}

form/templates/signup.html
{% extends "generic.html" %}
{% block contents %}
    <div class="row justify-content-md-center">
        <div class="col-sm-8">
            <div id="signupSuccess" class="alert alert-success" style="display:none">
                <p id="signupSuccessText">Thanks for signing up!<br/>
                    You'll be among the first to get notified for price changes. :D</p>
            </div>
            <div id="signupDuplicate" class="alert alert-success" style="display:none">
                <p id="signupDuplicateText">Fear not, you're already subscribed for this route!<br/>
                    You'll be among the first to get notified for price changes. :D</p>
            </div>
            <div id="signupError" class="alert alert-info" style="display:none">
                <p id="signupErrorText">Well this is embarrassing.<br/>
                    It looks like we're having trouble subscribing you for this route. :(</p>
            </div>
            <div class="jumbotron" id="jumbohome">
                <h1>Stay up to date with Ryanair Prices</h1>
                <div class="row">
                    <div class="col-sm-9">
                        <p class="lead">Never pay more than you should for a Ryanair flight ever again!</p>
                        <p>Give us your route details to be notified for price changes.</p>

                        <form id="signupForm" role="form" onsubmit="return false;">
                            <div class="form-group form-row">
                                <div class="col">
                                    <label for="fromAirport">From</label>
                                    <input required type="text" class="form-control" autocomplete="off" id="fromAirport" name="fromAirport" placeholder="Departure Airport Code">
                                </div>
                                <div class="col">
                                    <label for="toAirport">To</label>
                                    <input required type="text" class="form-control" autocomplete="off" id="toAirport" name="toAirport" placeholder="Arrival Airport Code">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="date">Date</label>
                                <input required type="date" class="form-control" id="date" name="date" placeholder="Date">
                            </div>
                            <div class="form-group">
                                <label for="email">Email address</label>
                                <input required type="email" class="form-control" id="email" name="email"
                                       placeholder="Your email address">
                            </div>
                            <div class="form-group" hidden>
                                <label for="username">Username</label>
                                <input type="username" class="form-control" id="username" name="username"
                                       value="{{ user.username }}">
                            </div>
                            <div class="form-group">
                                <label for="notifications">Interested in Email Notifications?</label>
                                <select class="form-control" name="notifications" id="notifications">
                                    <option>Yes</option>
                                    <option>No</option>
                                </select>
                            </div>
                            <button type="submit" id="signup" class="btn btn-primary">Submit</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% csrf_token %}

    <script type="text/javascript">
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $(document).ready(function () {
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            $("#signup").click(function () {
                $.post("{% url 'form:signup' %}", $("#signupForm").serialize(),
                    function (data) {
                        $(".alert").hide();
                        $("#signupSuccess").show();
                    }
                )
                    .error(function (xhr) {
                        $(".alert").hide();
                        switch (xhr.status) {
                            case 409:
                                $("#signupDuplicate").show();
                                break;
                            default:
                                $("#signupError").show();
                        }
                    })
            })
        })
    </script>

    {# AWS SDK Script FromAirport Auto-complete#}
    <script>
        $( function() {
                $.get( "https://s3.eu-west-3.amazonaws.com/cheapcheckerccproject/from_airports.json" ).done(function( data ) {
                    var airports = JSON.parse(data);
                    $( "#fromAirport" ).autocomplete( { source: airports } );
                });

        } );

    </script>

    {# AWS SDK Script ToAirport Auto-complete #}
    <script>
        $("#toAirport").click( function() {
            var from_airport = $( "#fromAirport" ).val();
            {# If departure airport is not set yet, then get all ryanair airports #}
            console.log(from_airport.substring(0,from_airport.indexOf(",")));
            if (!from_airport) {
                from_airport = "from_airports";
            }
            $.get( "https://s3.eu-west-3.amazonaws.com/cheapcheckerccproject/" + from_airport.substring(0,from_airport.indexOf(",")) + ".json" ).done(function( data ) {
                var ToAirports = JSON.parse(data);
                console.log(ToAirports);
                $( "#toAirport" ).autocomplete( { source: ToAirports } );
            });

        } );

    </script>

    {# AWS SDK Script FromAirport Auto-complete#}
{#    <script>#}
{#        $(document).ready( function() {#}
{##}
{#                var user_email = "{{  user.email }}";#}
{#                var user = "{{  user.username }}";#}
{#                console.log(user)#}
{#                console.log("Email: " + user_email);#}
{#                if(user_email) {#}
{#                    $("#email").val(user_email);#}
{#                    $("#email").hide();#}
{#                }#}
{##}
{#        } );#}
{##}
{#    </script>#}



{% endblock %}